# CMake generated Testfile for 
# Source directory: C:/Users/User/Projects/pdf-inst
# Build directory: C:/Users/User/Projects/pdf-inst/build-review
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(UnitTests "C:/Users/User/Projects/pdf-inst/build-review/UnitTests.exe")
set_tests_properties(UnitTests PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1026;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestInterfaces "C:/Users/User/Projects/pdf-inst/build-review/TestInterfaces.exe")
set_tests_properties(TestInterfaces PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;interfaces;commands;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1044;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExpiryInterface "C:/Users/User/Projects/pdf-inst/build-review/TestExpiryInterface.exe")
set_tests_properties(TestExpiryInterface PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;interfaces;security;expiry;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1069;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(SmokeTest "C:/Users/User/Projects/pdf-inst/build-review/SmokeTest.exe")
set_tests_properties(SmokeTest PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "smoke;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1086;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSanitization "C:/Users/User/Projects/pdf-inst/build-review/TestSanitization.exe")
set_tests_properties(TestSanitization PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;sanitization;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1104;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAutosave "C:/Users/User/Projects/pdf-inst/build-review/TestAutosave.exe")
set_tests_properties(TestAutosave PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;autosave;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1121;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDocumentIdentity "C:/Users/User/Projects/pdf-inst/build-review/TestDocumentIdentity.exe")
set_tests_properties(TestDocumentIdentity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;session;identity;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1155;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatesBatchSafety "C:/Users/User/Projects/pdf-inst/build-review/TestBatesBatchSafety.exe")
set_tests_properties(TestBatesBatchSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;bates;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1188;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRecoverySave "C:/Users/User/Projects/pdf-inst/build-review/TestRecoverySave.exe")
set_tests_properties(TestRecoverySave PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;recovery;session;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1221;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadOnlyGate "C:/Users/User/Projects/pdf-inst/build-review/TestReadOnlyGate.exe")
set_tests_properties(TestReadOnlyGate PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;readonly;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1254;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSidecarReopenState "C:/Users/User/Projects/pdf-inst/build-review/TestSidecarReopenState.exe")
set_tests_properties(TestSidecarReopenState PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;annotations;sidecar;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1288;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureValidationMock "C:/Users/User/Projects/pdf-inst/build-review/TestSignatureValidationMock.exe")
set_tests_properties(TestSignatureValidationMock PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;signatures;mock;interface;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1305;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRobustness "C:/Users/User/Projects/pdf-inst/build-review/TestRobustness.exe")
set_tests_properties(TestRobustness PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;robustness;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1322;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSecretStore "C:/Users/User/Projects/pdf-inst/build-review/TestSecretStore.exe")
set_tests_properties(TestSecretStore PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;secrets;privacy;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1339;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureValidation "C:/Users/User/Projects/pdf-inst/build-review/TestSignatureValidation.exe")
set_tests_properties(TestSignatureValidation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;real-crypto;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1363;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureRealCrypto "C:/Users/User/Projects/pdf-inst/build-review/TestSignatureRealCrypto.exe")
set_tests_properties(TestSignatureRealCrypto PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;crypto;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1402;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEraseSignedGuard "C:/Users/User/Projects/pdf-inst/build-review/TestEraseSignedGuard.exe")
set_tests_properties(TestEraseSignedGuard PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;erase;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1442;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureAppearance "C:/Users/User/Projects/pdf-inst/build-review/TestSignatureAppearance.exe")
set_tests_properties(TestSignatureAppearance PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;appearance;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1480;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOptimizeSignedGuard "C:/Users/User/Projects/pdf-inst/build-review/TestOptimizeSignedGuard.exe")
set_tests_properties(TestOptimizeSignedGuard PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;compression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1516;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestImageDedup "C:/Users/User/Projects/pdf-inst/build-review/TestImageDedup.exe")
set_tests_properties(TestImageDedup PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;compression;optimize;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1547;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestChain1 "C:/Users/User/Projects/pdf-inst/build-review/TestChain1.exe")
set_tests_properties(TestChain1 PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;chain1;provenance;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1567;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedaction "C:/Users/User/Projects/pdf-inst/build-review/TestRedaction.exe")
set_tests_properties(TestRedaction PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;redaction;regression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1584;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDedupSMask "C:/Users/User/Projects/pdf-inst/build-review/TestDedupSMask.exe")
set_tests_properties(TestDedupSMask PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;dedup;regression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1612;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompressJpegReencode "C:/Users/User/Projects/pdf-inst/build-review/TestCompressJpegReencode.exe")
set_tests_properties(TestCompressJpegReencode PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;jpeg;regression;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1640;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOptimizeEstimate "C:/Users/User/Projects/pdf-inst/build-review/TestOptimizeEstimate.exe")
set_tests_properties(TestOptimizeEstimate PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;estimate;regression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1668;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRapidOcr "C:/Users/User/Projects/pdf-inst/build-review/TestRapidOcr.exe")
set_tests_properties(TestRapidOcr PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;ml;rapidocr;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1694;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLayoutEnsemble "C:/Users/User/Projects/pdf-inst/build-review/TestLayoutEnsemble.exe")
set_tests_properties(TestLayoutEnsemble PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;layout;ensemble;iou;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1712;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrPipeline "C:/Users/User/Projects/pdf-inst/build-review/TestOcrPipeline.exe")
set_tests_properties(TestOcrPipeline PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;pipeline;rover;timing;cross-page;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1730;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrReviewLifecycle "C:/Users/User/Projects/pdf-inst/build-review/TestOcrReviewLifecycle.exe")
set_tests_properties(TestOcrReviewLifecycle PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;lifecycle;review;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1756;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrVerifyNavigation "C:/Users/User/Projects/pdf-inst/build-review/TestOcrVerifyNavigation.exe")
set_tests_properties(TestOcrVerifyNavigation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;review;navigation;u03;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1782;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrPreprocessor "C:/Users/User/Projects/pdf-inst/build-review/TestOcrPreprocessor.exe")
set_tests_properties(TestOcrPreprocessor PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;preprocess;orientation;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1800;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrDjotMapper "C:/Users/User/Projects/pdf-inst/build-review/TestOcrDjotMapper.exe")
set_tests_properties(TestOcrDjotMapper PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;mapper;djot;structural;roundtrip;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1818;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestThreadSafety "C:/Users/User/Projects/pdf-inst/build-review/TestThreadSafety.exe")
set_tests_properties(TestThreadSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;threads;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1835;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEncryption "C:/Users/User/Projects/pdf-inst/build-review/TestEncryption.exe")
set_tests_properties(TestEncryption PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;encryption;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1855;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestResourceLimits "C:/Users/User/Projects/pdf-inst/build-review/TestResourceLimits.exe")
set_tests_properties(TestResourceLimits PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;resources;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1872;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestControllers "C:/Users/User/Projects/pdf-inst/build-review/TestControllers.exe")
set_tests_properties(TestControllers PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;controllers;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1899;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRibbonIntegrity "C:/Users/User/Projects/pdf-inst/build-review/TestRibbonIntegrity.exe")
set_tests_properties(TestRibbonIntegrity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ribbon;integrity;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1925;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMenuBarIntegrity "C:/Users/User/Projects/pdf-inst/build-review/TestMenuBarIntegrity.exe")
set_tests_properties(TestMenuBarIntegrity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;menubar;integrity;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1951;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestIntegration "C:/Users/User/Projects/pdf-inst/build-review/TestIntegration.exe")
set_tests_properties(TestIntegration PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;e2e;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1969;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPerformance "C:/Users/User/Projects/pdf-inst/build-review/TestPerformance.exe")
set_tests_properties(TestPerformance PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "performance;benchmark;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1986;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestVeraPdf "C:/Users/User/Projects/pdf-inst/build-review/TestVeraPdf.exe")
set_tests_properties(TestVeraPdf PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;integration;pdfa;verapdf;subprocess" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2001;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadingOrderAsync "C:/Users/User/Projects/pdf-inst/build-review/TestReadingOrderAsync.exe")
set_tests_properties(TestReadingOrderAsync PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pdfa;accessibility;reading-order;async;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2017;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLaneScheduler "C:/Users/User/Projects/pdf-inst/build-review/TestLaneScheduler.exe")
set_tests_properties(TestLaneScheduler PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;concurrency;scheduling;lane-scheduler;qt" RUN_SERIAL "TRUE" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2032;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormBuilder "C:/Users/User/Projects/pdf-inst/build-review/TestFormBuilder.exe")
set_tests_properties(TestFormBuilder PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;builder;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2071;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormPersistence "C:/Users/User/Projects/pdf-inst/build-review/TestFormPersistence.exe")
set_tests_properties(TestFormPersistence PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2107;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompareEntry "C:/Users/User/Projects/pdf-inst/build-review/TestCompareEntry.exe")
set_tests_properties(TestCompareEntry PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;compare;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2133;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompareIntegration "C:/Users/User/Projects/pdf-inst/build-review/TestCompareIntegration.exe")
set_tests_properties(TestCompareIntegration PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;compare;integration;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2164;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPagesMode "C:/Users/User/Projects/pdf-inst/build-review/TestPagesMode.exe")
set_tests_properties(TestPagesMode PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;pages;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2190;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPageLabels "C:/Users/User/Projects/pdf-inst/build-review/TestPageLabels.exe")
set_tests_properties(TestPageLabels PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;pagelabels;core;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2223;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchMode "C:/Users/User/Projects/pdf-inst/build-review/TestBatchMode.exe")
set_tests_properties(TestBatchMode PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;batch;ui;qt;headless" RESOURCE_LOCK "BatchModeIO" RUN_SERIAL "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2250;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchOcrLanguage "C:/Users/User/Projects/pdf-inst/build-review/TestBatchOcrLanguage.exe")
set_tests_properties(TestBatchOcrLanguage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;batch;ocr;language;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2280;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrPreprocessPrefs "C:/Users/User/Projects/pdf-inst/build-review/TestOcrPreprocessPrefs.exe")
set_tests_properties(TestOcrPreprocessPrefs PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;preprocess;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2308;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatesCrossDoc "C:/Users/User/Projects/pdf-inst/build-review/TestBatesCrossDoc.exe")
set_tests_properties(TestBatesCrossDoc PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;bates;batch;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2337;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOpenRouting "C:/Users/User/Projects/pdf-inst/build-review/TestOpenRouting.exe")
set_tests_properties(TestOpenRouting PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;import;open;routing;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2367;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExcisionCorruption "C:/Users/User/Projects/pdf-inst/build-review/TestExcisionCorruption.exe")
set_tests_properties(TestExcisionCorruption PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;excision;corruption;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2395;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchOpsCoverage "C:/Users/User/Projects/pdf-inst/build-review/TestBatchOpsCoverage.exe")
set_tests_properties(TestBatchOpsCoverage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;batch;watermark;pdfa;merge;redact;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2436;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadingOrderThreshold "C:/Users/User/Projects/pdf-inst/build-review/TestReadingOrderThreshold.exe")
set_tests_properties(TestReadingOrderThreshold PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;accessibility;pdfa;reading-order;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2465;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLinkBookmarkRoundTrip "C:/Users/User/Projects/pdf-inst/build-review/TestLinkBookmarkRoundTrip.exe")
set_tests_properties(TestLinkBookmarkRoundTrip PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;sanitize;links;roundtrip;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2494;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureSessionCache "C:/Users/User/Projects/pdf-inst/build-review/TestSignatureSessionCache.exe")
set_tests_properties(TestSignatureSessionCache PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;cache;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2523;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCapabilityRegistry "C:/Users/User/Projects/pdf-inst/build-review/TestCapabilityRegistry.exe")
set_tests_properties(TestCapabilityRegistry PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;capability;u08;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2557;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTaskNavRegistry "C:/Users/User/Projects/pdf-inst/build-review/TestTaskNavRegistry.exe")
set_tests_properties(TestTaskNavRegistry PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;navigation;tasknav;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2584;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestScreenStateSync "C:/Users/User/Projects/pdf-inst/build-review/TestScreenStateSync.exe")
set_tests_properties(TestScreenStateSync PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;navigation;sync;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2611;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRibbonCollapse "C:/Users/User/Projects/pdf-inst/build-review/TestRibbonCollapse.exe")
set_tests_properties(TestRibbonCollapse PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;ribbon;collapse;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2638;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestStatusBarSlim "C:/Users/User/Projects/pdf-inst/build-review/TestStatusBarSlim.exe")
set_tests_properties(TestStatusBarSlim PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;statusbar;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2675;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCommentsReview "C:/Users/User/Projects/pdf-inst/build-review/TestCommentsReview.exe")
set_tests_properties(TestCommentsReview PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;comments;review;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2704;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestWelcomeLayout "C:/Users/User/Projects/pdf-inst/build-review/TestWelcomeLayout.exe")
set_tests_properties(TestWelcomeLayout PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ui;welcome;layout;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2734;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureBadges "C:/Users/User/Projects/pdf-inst/build-review/TestSignatureBadges.exe")
set_tests_properties(TestSignatureBadges PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;badge;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2767;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchOcrConfidence "C:/Users/User/Projects/pdf-inst/build-review/TestBatchOcrConfidence.exe")
set_tests_properties(TestBatchOcrConfidence PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;batch;ocr;confidence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2793;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestInspector "C:/Users/User/Projects/pdf-inst/build-review/TestInspector.exe")
set_tests_properties(TestInspector PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;inspector;properties;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2819;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPatternRedact "C:/Users/User/Projects/pdf-inst/build-review/TestPatternRedact.exe")
set_tests_properties(TestPatternRedact PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;redaction;patterns;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2845;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDjotRoundtrip "C:/Users/User/Projects/pdf-inst/build-review/TestDjotRoundtrip.exe")
set_tests_properties(TestDjotRoundtrip PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;djot;codec;provenance" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2868;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDjotFuzz "C:/Users/User/Projects/pdf-inst/build-review/TestDjotFuzz.exe")
set_tests_properties(TestDjotFuzz PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;djot;fuzz;codec;roundtrip" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2894;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestUpdateChecker "C:/Users/User/Projects/pdf-inst/build-review/TestUpdateChecker.exe")
set_tests_properties(TestUpdateChecker PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;update;security;qt;headless" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2916;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestWatermarkFont "C:/Users/User/Projects/pdf-inst/build-review/TestWatermarkFont.exe")
set_tests_properties(TestWatermarkFont PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;watermark;font;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2941;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrLanguage "C:/Users/User/Projects/pdf-inst/build-review/TestOcrLanguage.exe")
set_tests_properties(TestOcrLanguage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;language;qt;headless" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2957;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactClearMarks "C:/Users/User/Projects/pdf-inst/build-review/TestRedactClearMarks.exe")
set_tests_properties(TestRedactClearMarks PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;security;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2973;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLinkSchemeSafety "C:/Users/User/Projects/pdf-inst/build-review/TestLinkSchemeSafety.exe")
set_tests_properties(TestLinkSchemeSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;navigation;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2985;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestThumbnailZoom "C:/Users/User/Projects/pdf-inst/build-review/TestThumbnailZoom.exe")
set_tests_properties(TestThumbnailZoom PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;search;navigation;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2993;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMergeSuccess "C:/Users/User/Projects/pdf-inst/build-review/TestMergeSuccess.exe")
set_tests_properties(TestMergeSuccess PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;merge;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3001;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFillFormLock "C:/Users/User/Projects/pdf-inst/build-review/TestFillFormLock.exe")
set_tests_properties(TestFillFormLock PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3033;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFillFormNoOp "C:/Users/User/Projects/pdf-inst/build-review/TestFillFormNoOp.exe")
set_tests_properties(TestFillFormNoOp PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3065;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadingOrderInheritance "C:/Users/User/Projects/pdf-inst/build-review/TestReadingOrderInheritance.exe")
set_tests_properties(TestReadingOrderInheritance PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;accessibility;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3075;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestShapeInkPersistence "C:/Users/User/Projects/pdf-inst/build-review/TestShapeInkPersistence.exe")
set_tests_properties(TestShapeInkPersistence PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;annotations;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3095;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMeasurePanelHonesty "C:/Users/User/Projects/pdf-inst/build-review/TestMeasurePanelHonesty.exe")
set_tests_properties(TestMeasurePanelHonesty PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;measure;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3110;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMeasureCore "C:/Users/User/Projects/pdf-inst/build-review/TestMeasureCore.exe")
set_tests_properties(TestMeasureCore PROPERTIES  LABELS "unit;measure;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3122;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMeasureRoundTrip "C:/Users/User/Projects/pdf-inst/build-review/TestMeasureRoundTrip.exe")
set_tests_properties(TestMeasureRoundTrip PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;measure;annotations;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3145;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompressStripSanitize "C:/Users/User/Projects/pdf-inst/build-review/TestCompressStripSanitize.exe")
set_tests_properties(TestCompressStripSanitize PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;sanitization;privacy;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3165;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompressDialogHonesty "C:/Users/User/Projects/pdf-inst/build-review/TestCompressDialogHonesty.exe")
set_tests_properties(TestCompressDialogHonesty PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;honesty;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3192;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFieldMetadata "C:/Users/User/Projects/pdf-inst/build-review/TestFieldMetadata.exe")
set_tests_properties(TestFieldMetadata PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3228;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormSafety "C:/Users/User/Projects/pdf-inst/build-review/TestFormSafety.exe")
set_tests_properties(TestFormSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3260;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormJsCalc "C:/Users/User/Projects/pdf-inst/build-review/TestFormJsCalc.exe")
set_tests_properties(TestFormJsCalc PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-js;javascript;persistence;qt;headless" TIMEOUT "240" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3299;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEngineSave "C:/Users/User/Projects/pdf-inst/build-review/TestEngineSave.exe")
set_tests_properties(TestEngineSave PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;engine;save;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3331;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEncryptedPackageSafeWrite "C:/Users/User/Projects/pdf-inst/build-review/TestEncryptedPackageSafeWrite.exe")
set_tests_properties(TestEncryptedPackageSafeWrite PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;export;safesave;shell;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3344;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPrintJob "C:/Users/User/Projects/pdf-inst/build-review/TestPrintJob.exe")
set_tests_properties(TestPrintJob PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;print;ui;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3365;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTempOwnership "C:/Users/User/Projects/pdf-inst/build-review/TestTempOwnership.exe")
set_tests_properties(TestTempOwnership PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;temp;infrastructure;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3378;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCleanupCli "C:/Users/User/Projects/pdf-inst/build-review/TestCleanupCli.exe")
set_tests_properties(TestCleanupCli PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;tools;cleanup-cli;infrastructure;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3393;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormUndo "C:/Users/User/Projects/pdf-inst/build-review/TestFormUndo.exe")
set_tests_properties(TestFormUndo PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;undo;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3425;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestValidateAllSignatures "C:/Users/User/Projects/pdf-inst/build-review/TestValidateAllSignatures.exe")
set_tests_properties(TestValidateAllSignatures PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;security;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3435;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExportPathBadge "C:/Users/User/Projects/pdf-inst/build-review/TestExportPathBadge.exe")
set_tests_properties(TestExportPathBadge PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;export;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3445;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestImageEditWiring "C:/Users/User/Projects/pdf-inst/build-review/TestImageEditWiring.exe")
set_tests_properties(TestImageEditWiring PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;editing;images;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3455;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactSanitizeBundle "C:/Users/User/Projects/pdf-inst/build-review/TestRedactSanitizeBundle.exe")
set_tests_properties(TestRedactSanitizeBundle PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;sanitization;security;privacy;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3475;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactTransaction "C:/Users/User/Projects/pdf-inst/build-review/TestRedactTransaction.exe")
set_tests_properties(TestRedactTransaction PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;transaction;security;privacy;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3512;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactionProof "C:/Users/User/Projects/pdf-inst/build-review/TestRedactionProof.exe")
set_tests_properties(TestRedactionProof PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;proof;security;privacy;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3555;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPptxOverlayAlpha "C:/Users/User/Projects/pdf-inst/build-review/TestPptxOverlayAlpha.exe")
set_tests_properties(TestPptxOverlayAlpha PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;pptx;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3569;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAutoDetectHeuristic "C:/Users/User/Projects/pdf-inst/build-review/TestAutoDetectHeuristic.exe")
set_tests_properties(TestAutoDetectHeuristic PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;autodetect;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3601;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestConversionExtraction "C:/Users/User/Projects/pdf-inst/build-review/TestConversionExtraction.exe")
set_tests_properties(TestConversionExtraction PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;extraction;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3611;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTextExtractionCoords "C:/Users/User/Projects/pdf-inst/build-review/TestTextExtractionCoords.exe")
set_tests_properties(TestTextExtractionCoords PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;pptx;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3621;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEraseWiring "C:/Users/User/Projects/pdf-inst/build-review/TestEraseWiring.exe")
set_tests_properties(TestEraseWiring PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;editing;erase;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3631;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAnnotationToolBar "C:/Users/User/Projects/pdf-inst/build-review/TestAnnotationToolBar.exe")
set_tests_properties(TestAnnotationToolBar PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;annotations;toolbar;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3641;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestViewerRotation "C:/Users/User/Projects/pdf-inst/build-review/TestViewerRotation.exe")
set_tests_properties(TestViewerRotation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;rotation;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3651;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTwoPageOverlay "C:/Users/User/Projects/pdf-inst/build-review/TestTwoPageOverlay.exe")
set_tests_properties(TestTwoPageOverlay PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;twopage;regression;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3674;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignaturePicker "C:/Users/User/Projects/pdf-inst/build-review/TestSignaturePicker.exe")
set_tests_properties(TestSignaturePicker PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;picker;regression;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3701;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrAcceptSeam "C:/Users/User/Projects/pdf-inst/build-review/TestOcrAcceptSeam.exe")
set_tests_properties(TestOcrAcceptSeam PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;accept;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3715;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSearchFlags "C:/Users/User/Projects/pdf-inst/build-review/TestSearchFlags.exe")
set_tests_properties(TestSearchFlags PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;search;flags;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3725;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExportPresets "C:/Users/User/Projects/pdf-inst/build-review/TestExportPresets.exe")
set_tests_properties(TestExportPresets PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;export;presets;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3735;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrAcceptScope "C:/Users/User/Projects/pdf-inst/build-review/TestOcrAcceptScope.exe")
set_tests_properties(TestOcrAcceptScope PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;accept;honesty;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3745;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestViewerLinkSeam "C:/Users/User/Projects/pdf-inst/build-review/TestViewerLinkSeam.exe")
set_tests_properties(TestViewerLinkSeam PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;links;seam;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3756;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestHyperlinkNavigation "C:/Users/User/Projects/pdf-inst/build-review/TestHyperlinkNavigation.exe")
set_tests_properties(TestHyperlinkNavigation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;links;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3776;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactMarkAll "C:/Users/User/Projects/pdf-inst/build-review/TestRedactMarkAll.exe")
set_tests_properties(TestRedactMarkAll PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3796;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactApplyMarks "C:/Users/User/Projects/pdf-inst/build-review/TestRedactApplyMarks.exe")
set_tests_properties(TestRedactApplyMarks PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;security;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3816;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAnnotationDjot "C:/Users/User/Projects/pdf-inst/build-review/TestAnnotationDjot.exe")
set_tests_properties(TestAnnotationDjot PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;annot;djot;richtext;roundtrip;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3837;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAiProvider "C:/Users/User/Projects/pdf-inst/build-review/TestAiProvider.exe")
set_tests_properties(TestAiProvider PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ai;provider;mock;qt;headless" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3854;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOllamaProvider "C:/Users/User/Projects/pdf-inst/build-review/TestOllamaProvider.exe")
set_tests_properties(TestOllamaProvider PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ai;ollama;provider;lifetime;endpoint;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3874;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDiffEngine "C:/Users/User/Projects/pdf-inst/build-review/TestDiffEngine.exe")
set_tests_properties(TestDiffEngine PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;diff;lcs;myers;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3891;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOfficeImport "C:/Users/User/Projects/pdf-inst/build-review/TestOfficeImport.exe")
set_tests_properties(TestOfficeImport PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;convert;office;import;images;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3910;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMrcPipeline "C:/Users/User/Projects/pdf-inst/build-review/TestMrcPipeline.exe")
set_tests_properties(TestMrcPipeline PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;mrc;compression;pdfa;sandwich;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3929;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCheckedMutationCoverage "C:/Users/User/Projects/pdf-inst/build-review/TestCheckedMutationCoverage.exe")
set_tests_properties(TestCheckedMutationCoverage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;history;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3992;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestHistoryIntegrity "C:/Users/User/Projects/pdf-inst/build-review/TestHistoryIntegrity.exe")
set_tests_properties(TestHistoryIntegrity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;history;commands;undo;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4031;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPersistenceOutcomes "C:/Users/User/Projects/pdf-inst/build-review/TestPersistenceOutcomes.exe")
set_tests_properties(TestPersistenceOutcomes PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;session;persistence;identity;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4064;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
subdirs("third_party")
subdirs("src/docmodel")
subdirs("src/pdfws_djot")
subdirs("third_party/jbig2enc")
