# CMake generated Testfile for 
# Source directory: C:/Users/User/Projects/pdf-inst
# Build directory: C:/Users/User/Projects/pdf-inst/build-formjs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(UnitTests "C:/Users/User/Projects/pdf-inst/build-formjs/UnitTests.exe")
set_tests_properties(UnitTests PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1033;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestInterfaces "C:/Users/User/Projects/pdf-inst/build-formjs/TestInterfaces.exe")
set_tests_properties(TestInterfaces PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;interfaces;commands;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1051;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExpiryInterface "C:/Users/User/Projects/pdf-inst/build-formjs/TestExpiryInterface.exe")
set_tests_properties(TestExpiryInterface PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;interfaces;security;expiry;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1076;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(SmokeTest "C:/Users/User/Projects/pdf-inst/build-formjs/SmokeTest.exe")
set_tests_properties(SmokeTest PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "smoke;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1093;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSanitization "C:/Users/User/Projects/pdf-inst/build-formjs/TestSanitization.exe")
set_tests_properties(TestSanitization PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;sanitization;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1111;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAutosave "C:/Users/User/Projects/pdf-inst/build-formjs/TestAutosave.exe")
set_tests_properties(TestAutosave PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;autosave;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1128;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDocumentIdentity "C:/Users/User/Projects/pdf-inst/build-formjs/TestDocumentIdentity.exe")
set_tests_properties(TestDocumentIdentity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;session;identity;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1162;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatesBatchSafety "C:/Users/User/Projects/pdf-inst/build-formjs/TestBatesBatchSafety.exe")
set_tests_properties(TestBatesBatchSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;bates;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1195;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRecoverySave "C:/Users/User/Projects/pdf-inst/build-formjs/TestRecoverySave.exe")
set_tests_properties(TestRecoverySave PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;recovery;session;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1228;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadOnlyGate "C:/Users/User/Projects/pdf-inst/build-formjs/TestReadOnlyGate.exe")
set_tests_properties(TestReadOnlyGate PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;readonly;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1261;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSidecarReopenState "C:/Users/User/Projects/pdf-inst/build-formjs/TestSidecarReopenState.exe")
set_tests_properties(TestSidecarReopenState PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;annotations;sidecar;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1295;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureValidationMock "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignatureValidationMock.exe")
set_tests_properties(TestSignatureValidationMock PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;signatures;mock;interface;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1312;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRobustness "C:/Users/User/Projects/pdf-inst/build-formjs/TestRobustness.exe")
set_tests_properties(TestRobustness PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;robustness;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1329;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSecretStore "C:/Users/User/Projects/pdf-inst/build-formjs/TestSecretStore.exe")
set_tests_properties(TestSecretStore PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;secrets;privacy;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1346;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureValidation "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignatureValidation.exe")
set_tests_properties(TestSignatureValidation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;real-crypto;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1370;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureRealCrypto "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignatureRealCrypto.exe")
set_tests_properties(TestSignatureRealCrypto PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;crypto;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1409;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEraseSignedGuard "C:/Users/User/Projects/pdf-inst/build-formjs/TestEraseSignedGuard.exe")
set_tests_properties(TestEraseSignedGuard PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;erase;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1449;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureAppearance "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignatureAppearance.exe")
set_tests_properties(TestSignatureAppearance PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;appearance;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1487;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOptimizeSignedGuard "C:/Users/User/Projects/pdf-inst/build-formjs/TestOptimizeSignedGuard.exe")
set_tests_properties(TestOptimizeSignedGuard PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;security;signatures;compression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1523;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestImageDedup "C:/Users/User/Projects/pdf-inst/build-formjs/TestImageDedup.exe")
set_tests_properties(TestImageDedup PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;compression;optimize;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1554;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestChain1 "C:/Users/User/Projects/pdf-inst/build-formjs/TestChain1.exe")
set_tests_properties(TestChain1 PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;chain1;provenance;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1574;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedaction "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedaction.exe")
set_tests_properties(TestRedaction PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;redaction;regression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1591;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDedupSMask "C:/Users/User/Projects/pdf-inst/build-formjs/TestDedupSMask.exe")
set_tests_properties(TestDedupSMask PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;dedup;regression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1619;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompressJpegReencode "C:/Users/User/Projects/pdf-inst/build-formjs/TestCompressJpegReencode.exe")
set_tests_properties(TestCompressJpegReencode PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;jpeg;regression;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1647;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOptimizeEstimate "C:/Users/User/Projects/pdf-inst/build-formjs/TestOptimizeEstimate.exe")
set_tests_properties(TestOptimizeEstimate PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;estimate;regression;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1675;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRapidOcr "C:/Users/User/Projects/pdf-inst/build-formjs/TestRapidOcr.exe")
set_tests_properties(TestRapidOcr PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;ml;rapidocr;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1701;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLayoutEnsemble "C:/Users/User/Projects/pdf-inst/build-formjs/TestLayoutEnsemble.exe")
set_tests_properties(TestLayoutEnsemble PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;layout;ensemble;iou;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1719;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrPipeline "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrPipeline.exe")
set_tests_properties(TestOcrPipeline PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;pipeline;rover;timing;cross-page;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1737;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrReviewLifecycle "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrReviewLifecycle.exe")
set_tests_properties(TestOcrReviewLifecycle PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;lifecycle;review;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1763;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrVerifyNavigation "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrVerifyNavigation.exe")
set_tests_properties(TestOcrVerifyNavigation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;review;navigation;u03;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1789;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrPreprocessor "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrPreprocessor.exe")
set_tests_properties(TestOcrPreprocessor PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;preprocess;orientation;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1807;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrDjotMapper "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrDjotMapper.exe")
set_tests_properties(TestOcrDjotMapper PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ocr;mapper;djot;structural;roundtrip;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1825;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestThreadSafety "C:/Users/User/Projects/pdf-inst/build-formjs/TestThreadSafety.exe")
set_tests_properties(TestThreadSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;threads;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1842;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEncryption "C:/Users/User/Projects/pdf-inst/build-formjs/TestEncryption.exe")
set_tests_properties(TestEncryption PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;encryption;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1862;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestResourceLimits "C:/Users/User/Projects/pdf-inst/build-formjs/TestResourceLimits.exe")
set_tests_properties(TestResourceLimits PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;resources;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1879;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestControllers "C:/Users/User/Projects/pdf-inst/build-formjs/TestControllers.exe")
set_tests_properties(TestControllers PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;controllers;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1906;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRibbonIntegrity "C:/Users/User/Projects/pdf-inst/build-formjs/TestRibbonIntegrity.exe")
set_tests_properties(TestRibbonIntegrity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ribbon;integrity;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1932;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMenuBarIntegrity "C:/Users/User/Projects/pdf-inst/build-formjs/TestMenuBarIntegrity.exe")
set_tests_properties(TestMenuBarIntegrity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;menubar;integrity;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1958;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestIntegration "C:/Users/User/Projects/pdf-inst/build-formjs/TestIntegration.exe")
set_tests_properties(TestIntegration PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "integration;e2e;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1976;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPerformance "C:/Users/User/Projects/pdf-inst/build-formjs/TestPerformance.exe")
set_tests_properties(TestPerformance PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "performance;benchmark;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;1993;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestVeraPdf "C:/Users/User/Projects/pdf-inst/build-formjs/TestVeraPdf.exe")
set_tests_properties(TestVeraPdf PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;integration;pdfa;verapdf;subprocess" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2008;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadingOrderAsync "C:/Users/User/Projects/pdf-inst/build-formjs/TestReadingOrderAsync.exe")
set_tests_properties(TestReadingOrderAsync PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pdfa;accessibility;reading-order;async;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2024;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLaneScheduler "C:/Users/User/Projects/pdf-inst/build-formjs/TestLaneScheduler.exe")
set_tests_properties(TestLaneScheduler PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;concurrency;scheduling;lane-scheduler;qt" RUN_SERIAL "TRUE" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2039;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormBuilder "C:/Users/User/Projects/pdf-inst/build-formjs/TestFormBuilder.exe")
set_tests_properties(TestFormBuilder PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;builder;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2078;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormPersistence "C:/Users/User/Projects/pdf-inst/build-formjs/TestFormPersistence.exe")
set_tests_properties(TestFormPersistence PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2114;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompareEntry "C:/Users/User/Projects/pdf-inst/build-formjs/TestCompareEntry.exe")
set_tests_properties(TestCompareEntry PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;compare;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2140;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompareIntegration "C:/Users/User/Projects/pdf-inst/build-formjs/TestCompareIntegration.exe")
set_tests_properties(TestCompareIntegration PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;compare;integration;ui;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2171;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPagesMode "C:/Users/User/Projects/pdf-inst/build-formjs/TestPagesMode.exe")
set_tests_properties(TestPagesMode PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;pages;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2197;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPageLabels "C:/Users/User/Projects/pdf-inst/build-formjs/TestPageLabels.exe")
set_tests_properties(TestPageLabels PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;pagelabels;core;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2230;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchMode "C:/Users/User/Projects/pdf-inst/build-formjs/TestBatchMode.exe")
set_tests_properties(TestBatchMode PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;modes;batch;ui;qt;headless" RESOURCE_LOCK "BatchModeIO" RUN_SERIAL "TRUE" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2257;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchOcrLanguage "C:/Users/User/Projects/pdf-inst/build-formjs/TestBatchOcrLanguage.exe")
set_tests_properties(TestBatchOcrLanguage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;batch;ocr;language;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2287;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrPreprocessPrefs "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrPreprocessPrefs.exe")
set_tests_properties(TestOcrPreprocessPrefs PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;preprocess;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2315;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatesCrossDoc "C:/Users/User/Projects/pdf-inst/build-formjs/TestBatesCrossDoc.exe")
set_tests_properties(TestBatesCrossDoc PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;bates;batch;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2344;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOpenRouting "C:/Users/User/Projects/pdf-inst/build-formjs/TestOpenRouting.exe")
set_tests_properties(TestOpenRouting PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;import;open;routing;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2374;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExcisionCorruption "C:/Users/User/Projects/pdf-inst/build-formjs/TestExcisionCorruption.exe")
set_tests_properties(TestExcisionCorruption PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;excision;corruption;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2402;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchOpsCoverage "C:/Users/User/Projects/pdf-inst/build-formjs/TestBatchOpsCoverage.exe")
set_tests_properties(TestBatchOpsCoverage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;batch;watermark;pdfa;merge;redact;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2443;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadingOrderThreshold "C:/Users/User/Projects/pdf-inst/build-formjs/TestReadingOrderThreshold.exe")
set_tests_properties(TestReadingOrderThreshold PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;accessibility;pdfa;reading-order;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2472;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLinkBookmarkRoundTrip "C:/Users/User/Projects/pdf-inst/build-formjs/TestLinkBookmarkRoundTrip.exe")
set_tests_properties(TestLinkBookmarkRoundTrip PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;sanitize;links;roundtrip;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2501;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureSessionCache "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignatureSessionCache.exe")
set_tests_properties(TestSignatureSessionCache PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;cache;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2530;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCapabilityRegistry "C:/Users/User/Projects/pdf-inst/build-formjs/TestCapabilityRegistry.exe")
set_tests_properties(TestCapabilityRegistry PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;capability;u08;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2564;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTaskNavRegistry "C:/Users/User/Projects/pdf-inst/build-formjs/TestTaskNavRegistry.exe")
set_tests_properties(TestTaskNavRegistry PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;navigation;tasknav;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2591;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestScreenStateSync "C:/Users/User/Projects/pdf-inst/build-formjs/TestScreenStateSync.exe")
set_tests_properties(TestScreenStateSync PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;navigation;sync;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2618;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRibbonCollapse "C:/Users/User/Projects/pdf-inst/build-formjs/TestRibbonCollapse.exe")
set_tests_properties(TestRibbonCollapse PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;ribbon;collapse;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2645;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestStatusBarSlim "C:/Users/User/Projects/pdf-inst/build-formjs/TestStatusBarSlim.exe")
set_tests_properties(TestStatusBarSlim PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;shell;statusbar;u02;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2682;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCommentsReview "C:/Users/User/Projects/pdf-inst/build-formjs/TestCommentsReview.exe")
set_tests_properties(TestCommentsReview PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;comments;review;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2711;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestWelcomeLayout "C:/Users/User/Projects/pdf-inst/build-formjs/TestWelcomeLayout.exe")
set_tests_properties(TestWelcomeLayout PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "ui;welcome;layout;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2741;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignatureBadges "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignatureBadges.exe")
set_tests_properties(TestSignatureBadges PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;badge;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2774;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestBatchOcrConfidence "C:/Users/User/Projects/pdf-inst/build-formjs/TestBatchOcrConfidence.exe")
set_tests_properties(TestBatchOcrConfidence PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;batch;ocr;confidence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2800;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestInspector "C:/Users/User/Projects/pdf-inst/build-formjs/TestInspector.exe")
set_tests_properties(TestInspector PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;inspector;properties;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2826;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPatternRedact "C:/Users/User/Projects/pdf-inst/build-formjs/TestPatternRedact.exe")
set_tests_properties(TestPatternRedact PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;redaction;patterns;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2852;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFindReplace "C:/Users/User/Projects/pdf-inst/build-formjs/TestFindReplace.exe")
set_tests_properties(TestFindReplace PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;edit;find-replace;t2-2;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2883;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReviewSummary "C:/Users/User/Projects/pdf-inst/build-formjs/TestReviewSummary.exe")
set_tests_properties(TestReviewSummary PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;comments;review-summary;t2-3;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2913;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDynamicStamps "C:/Users/User/Projects/pdf-inst/build-formjs/TestDynamicStamps.exe")
set_tests_properties(TestDynamicStamps PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;comments;stamps;t2-6;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2944;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAutoBookmarks "C:/Users/User/Projects/pdf-inst/build-formjs/TestAutoBookmarks.exe")
set_tests_properties(TestAutoBookmarks PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;edit;auto-bookmarks;t2-9;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2974;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDjotRoundtrip "C:/Users/User/Projects/pdf-inst/build-formjs/TestDjotRoundtrip.exe")
set_tests_properties(TestDjotRoundtrip PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;djot;codec;provenance" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;2997;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDjotFuzz "C:/Users/User/Projects/pdf-inst/build-formjs/TestDjotFuzz.exe")
set_tests_properties(TestDjotFuzz PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;djot;fuzz;codec;roundtrip" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3023;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestUpdateChecker "C:/Users/User/Projects/pdf-inst/build-formjs/TestUpdateChecker.exe")
set_tests_properties(TestUpdateChecker PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;update;security;qt;headless" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3045;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestWatermarkFont "C:/Users/User/Projects/pdf-inst/build-formjs/TestWatermarkFont.exe")
set_tests_properties(TestWatermarkFont PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;watermark;font;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3070;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrLanguage "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrLanguage.exe")
set_tests_properties(TestOcrLanguage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;language;qt;headless" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3086;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactClearMarks "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedactClearMarks.exe")
set_tests_properties(TestRedactClearMarks PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;security;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3102;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestLinkSchemeSafety "C:/Users/User/Projects/pdf-inst/build-formjs/TestLinkSchemeSafety.exe")
set_tests_properties(TestLinkSchemeSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;security;navigation;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3114;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestThumbnailZoom "C:/Users/User/Projects/pdf-inst/build-formjs/TestThumbnailZoom.exe")
set_tests_properties(TestThumbnailZoom PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;search;navigation;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3122;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMergeSuccess "C:/Users/User/Projects/pdf-inst/build-formjs/TestMergeSuccess.exe")
set_tests_properties(TestMergeSuccess PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;pages;merge;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3130;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFillFormLock "C:/Users/User/Projects/pdf-inst/build-formjs/TestFillFormLock.exe")
set_tests_properties(TestFillFormLock PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3162;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFillFormNoOp "C:/Users/User/Projects/pdf-inst/build-formjs/TestFillFormNoOp.exe")
set_tests_properties(TestFillFormNoOp PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3194;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestReadingOrderInheritance "C:/Users/User/Projects/pdf-inst/build-formjs/TestReadingOrderInheritance.exe")
set_tests_properties(TestReadingOrderInheritance PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;accessibility;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3204;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestShapeInkPersistence "C:/Users/User/Projects/pdf-inst/build-formjs/TestShapeInkPersistence.exe")
set_tests_properties(TestShapeInkPersistence PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;annotations;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3224;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMeasurePanelHonesty "C:/Users/User/Projects/pdf-inst/build-formjs/TestMeasurePanelHonesty.exe")
set_tests_properties(TestMeasurePanelHonesty PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;measure;ui;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3239;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMeasureCore "C:/Users/User/Projects/pdf-inst/build-formjs/TestMeasureCore.exe")
set_tests_properties(TestMeasureCore PROPERTIES  LABELS "unit;measure;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3251;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMeasureRoundTrip "C:/Users/User/Projects/pdf-inst/build-formjs/TestMeasureRoundTrip.exe")
set_tests_properties(TestMeasureRoundTrip PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;measure;annotations;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3274;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompressStripSanitize "C:/Users/User/Projects/pdf-inst/build-formjs/TestCompressStripSanitize.exe")
set_tests_properties(TestCompressStripSanitize PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;sanitization;privacy;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3294;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCompressDialogHonesty "C:/Users/User/Projects/pdf-inst/build-formjs/TestCompressDialogHonesty.exe")
set_tests_properties(TestCompressDialogHonesty PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;compression;honesty;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3321;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFieldMetadata "C:/Users/User/Projects/pdf-inst/build-formjs/TestFieldMetadata.exe")
set_tests_properties(TestFieldMetadata PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3357;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormSafety "C:/Users/User/Projects/pdf-inst/build-formjs/TestFormSafety.exe")
set_tests_properties(TestFormSafety PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3389;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormJsCalc "C:/Users/User/Projects/pdf-inst/build-formjs/TestFormJsCalc.exe")
set_tests_properties(TestFormJsCalc PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-js;javascript;persistence;qt;headless" TIMEOUT "240" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3428;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEngineSave "C:/Users/User/Projects/pdf-inst/build-formjs/TestEngineSave.exe")
set_tests_properties(TestEngineSave PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;engine;save;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3460;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEncryptedPackageSafeWrite "C:/Users/User/Projects/pdf-inst/build-formjs/TestEncryptedPackageSafeWrite.exe")
set_tests_properties(TestEncryptedPackageSafeWrite PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;export;safesave;shell;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3473;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPrintJob "C:/Users/User/Projects/pdf-inst/build-formjs/TestPrintJob.exe")
set_tests_properties(TestPrintJob PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;print;ui;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3494;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTempOwnership "C:/Users/User/Projects/pdf-inst/build-formjs/TestTempOwnership.exe")
set_tests_properties(TestTempOwnership PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;temp;infrastructure;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3507;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCleanupCli "C:/Users/User/Projects/pdf-inst/build-formjs/TestCleanupCli.exe")
set_tests_properties(TestCleanupCli PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;tools;cleanup-cli;infrastructure;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3522;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestFormUndo "C:/Users/User/Projects/pdf-inst/build-formjs/TestFormUndo.exe")
set_tests_properties(TestFormUndo PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;form-fields;undo;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3554;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestValidateAllSignatures "C:/Users/User/Projects/pdf-inst/build-formjs/TestValidateAllSignatures.exe")
set_tests_properties(TestValidateAllSignatures PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;security;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3564;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExportPathBadge "C:/Users/User/Projects/pdf-inst/build-formjs/TestExportPathBadge.exe")
set_tests_properties(TestExportPathBadge PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;export;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3574;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestImageEditWiring "C:/Users/User/Projects/pdf-inst/build-formjs/TestImageEditWiring.exe")
set_tests_properties(TestImageEditWiring PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;editing;images;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3584;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactSanitizeBundle "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedactSanitizeBundle.exe")
set_tests_properties(TestRedactSanitizeBundle PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;sanitization;security;privacy;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3604;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactTransaction "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedactTransaction.exe")
set_tests_properties(TestRedactTransaction PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;transaction;security;privacy;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3641;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactionProof "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedactionProof.exe")
set_tests_properties(TestRedactionProof PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;proof;security;privacy;qt;headless" TIMEOUT "180" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3684;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPptxOverlayAlpha "C:/Users/User/Projects/pdf-inst/build-formjs/TestPptxOverlayAlpha.exe")
set_tests_properties(TestPptxOverlayAlpha PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;pptx;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3698;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAutoDetectHeuristic "C:/Users/User/Projects/pdf-inst/build-formjs/TestAutoDetectHeuristic.exe")
set_tests_properties(TestAutoDetectHeuristic PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;forms;autodetect;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3730;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestConversionExtraction "C:/Users/User/Projects/pdf-inst/build-formjs/TestConversionExtraction.exe")
set_tests_properties(TestConversionExtraction PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;extraction;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3740;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTextExtractionCoords "C:/Users/User/Projects/pdf-inst/build-formjs/TestTextExtractionCoords.exe")
set_tests_properties(TestTextExtractionCoords PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;conversion;pptx;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3750;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestEraseWiring "C:/Users/User/Projects/pdf-inst/build-formjs/TestEraseWiring.exe")
set_tests_properties(TestEraseWiring PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;editing;erase;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3760;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAnnotationToolBar "C:/Users/User/Projects/pdf-inst/build-formjs/TestAnnotationToolBar.exe")
set_tests_properties(TestAnnotationToolBar PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;annotations;toolbar;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3770;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestViewerRotation "C:/Users/User/Projects/pdf-inst/build-formjs/TestViewerRotation.exe")
set_tests_properties(TestViewerRotation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;rotation;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3780;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestTwoPageOverlay "C:/Users/User/Projects/pdf-inst/build-formjs/TestTwoPageOverlay.exe")
set_tests_properties(TestTwoPageOverlay PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;twopage;regression;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3803;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSignaturePicker "C:/Users/User/Projects/pdf-inst/build-formjs/TestSignaturePicker.exe")
set_tests_properties(TestSignaturePicker PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;signatures;picker;regression;qt;headless" TIMEOUT "300" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3830;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrAcceptSeam "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrAcceptSeam.exe")
set_tests_properties(TestOcrAcceptSeam PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;accept;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3844;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestSearchFlags "C:/Users/User/Projects/pdf-inst/build-formjs/TestSearchFlags.exe")
set_tests_properties(TestSearchFlags PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;search;flags;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3854;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestExportPresets "C:/Users/User/Projects/pdf-inst/build-formjs/TestExportPresets.exe")
set_tests_properties(TestExportPresets PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;export;presets;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3864;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOcrAcceptScope "C:/Users/User/Projects/pdf-inst/build-formjs/TestOcrAcceptScope.exe")
set_tests_properties(TestOcrAcceptScope PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ocr;accept;honesty;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3874;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestViewerLinkSeam "C:/Users/User/Projects/pdf-inst/build-formjs/TestViewerLinkSeam.exe")
set_tests_properties(TestViewerLinkSeam PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;links;seam;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3885;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestHyperlinkNavigation "C:/Users/User/Projects/pdf-inst/build-formjs/TestHyperlinkNavigation.exe")
set_tests_properties(TestHyperlinkNavigation PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;viewing;links;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3905;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactMarkAll "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedactMarkAll.exe")
set_tests_properties(TestRedactMarkAll PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3925;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRedactApplyMarks "C:/Users/User/Projects/pdf-inst/build-formjs/TestRedactApplyMarks.exe")
set_tests_properties(TestRedactApplyMarks PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;redaction;security;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3945;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAnnotationDjot "C:/Users/User/Projects/pdf-inst/build-formjs/TestAnnotationDjot.exe")
set_tests_properties(TestAnnotationDjot PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;annot;djot;richtext;roundtrip;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3966;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestAiProvider "C:/Users/User/Projects/pdf-inst/build-formjs/TestAiProvider.exe")
set_tests_properties(TestAiProvider PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ai;provider;mock;qt;headless" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;3983;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOllamaProvider "C:/Users/User/Projects/pdf-inst/build-formjs/TestOllamaProvider.exe")
set_tests_properties(TestOllamaProvider PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;ai;ollama;provider;lifetime;endpoint;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4003;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestDiffEngine "C:/Users/User/Projects/pdf-inst/build-formjs/TestDiffEngine.exe")
set_tests_properties(TestDiffEngine PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;diff;lcs;myers;qt;headless" TIMEOUT "60" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4020;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestOfficeImport "C:/Users/User/Projects/pdf-inst/build-formjs/TestOfficeImport.exe")
set_tests_properties(TestOfficeImport PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;convert;office;import;images;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4039;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestMrcPipeline "C:/Users/User/Projects/pdf-inst/build-formjs/TestMrcPipeline.exe")
set_tests_properties(TestMrcPipeline PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;mrc;compression;pdfa;sandwich;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4058;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestCheckedMutationCoverage "C:/Users/User/Projects/pdf-inst/build-formjs/TestCheckedMutationCoverage.exe")
set_tests_properties(TestCheckedMutationCoverage PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;history;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4121;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestHistoryIntegrity "C:/Users/User/Projects/pdf-inst/build-formjs/TestHistoryIntegrity.exe")
set_tests_properties(TestHistoryIntegrity PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;history;commands;undo;persistence;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4160;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestPersistenceOutcomes "C:/Users/User/Projects/pdf-inst/build-formjs/TestPersistenceOutcomes.exe")
set_tests_properties(TestPersistenceOutcomes PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;session;persistence;identity;integration;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4193;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
add_test(TestRenderGuards "C:/Users/User/Projects/pdf-inst/build-formjs/TestRenderGuards.exe")
set_tests_properties(TestRenderGuards PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen" LABELS "unit;render;guards;perf04;qt;headless" TIMEOUT "120" _BACKTRACE_TRIPLES "C:/Users/User/Projects/pdf-inst/CMakeLists.txt;4246;add_test;C:/Users/User/Projects/pdf-inst/CMakeLists.txt;0;")
subdirs("third_party")
subdirs("src/docmodel")
subdirs("src/pdfws_djot")
subdirs("third_party/jbig2enc")
