// SPDX-License-Identifier: Apache-2.0
#pragma once

// ── UI redesign Phase 0 (plan 06 §7.1, ADR-UI-03 layer 1): CommandRegistry ──
// One catalogue of command PRESENTATION metadata — label, long name, tooltip,
// icon key, shortcut, control type, and the honest reason + alternative for a
// planned (visible, disabled) command — loaded from resources/commands.json.
//
// Ids ARE the app's canonical ToolId strings (no second id space). The file
// also carries the commands the redesign proposes but the app does not route
// yet (status "new-toolid" / "planned"); consumers treat those as planned.
//
// METADATA ONLY: the registry owns no QAction, no handler and no document
// state. Each window builds its own actions from these specs and dispatches
// through the existing ToolId routes (ADR-UI-03 layers 2 and 3).
//
// resources/commands.json is GENERATED by tools/ui/gen_commands_json.py from
// the redesign handoff's curated seed — edit the seed, then regenerate.

#include <QHash>
#include <QString>
#include <QStringList>

#include "core/ToolId.h"

namespace gp {

struct CommandSpec {
    QString id;                  ///< canonical ToolId string, or a planned/proposed id
    QString label;               ///< short label (source text; translate at the point of use)
    QString name;                ///< long accessible name; empty means "same as label"
    QString description;         ///< tooltip / accessible description
    QString icon;                ///< icon key, resolved by the icon provider
    QString shortcut;            ///< portable text such as "Ctrl+Z"; empty = none
    QString action;              ///< design action kind: "tool", "pane:redact", "fn:zoomIn", ...
    QString control;             ///< "" button, "tg" toggle, "m" menu, "ck" check, "sp" split, "g" gallery
    QString status;              ///< curation status: toolid, new-toolid, planned, shell, ...
    QString plannedReason;       ///< non-empty exactly when the command is planned
    QString plannedAlternative;  ///< the supported route to offer instead
    bool placeholder = false;    ///< label/description/icon still await design

    bool isPlanned() const { return !plannedReason.isEmpty(); }
    QString displayName() const { return name.isEmpty() ? label : name; }
};

class CommandRegistry {
public:
    /// The application registry, parsed once from the bundled :/gp/commands.json.
    static const CommandRegistry& instance();

    /// Parses a schema-1 commands.json document into this registry, replacing
    /// its contents. Returns false (and leaves the registry empty) on any
    /// malformed input, with a one-line reason in `error`.
    bool load(const QByteArray& json, QString* error = nullptr);

    const CommandSpec* find(const QString& id) const;
    const CommandSpec* find(ToolId id) const;
    /// Every command id, sorted.
    QStringList ids() const;
    /// ToolId strings that are deliberately internal (no command of their own),
    /// each with the recorded reason.
    const QHash<QString, QString>& internalToolIds() const { return m_internal; }

    int size() const { return int(m_specs.size()); }
    int schema() const { return m_schema; }

    static constexpr int kSchema = 1;

private:
    QHash<QString, CommandSpec> m_specs;
    QHash<QString, QString> m_internal;
    int m_schema = 0;
};

} // namespace gp
