set(OUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/DjotBundle.h")
file(WRITE "${OUT_FILE}" "#pragma once`n`n")

function(embed_file file_path var_name)
    file(READ "${file_path}" file_content HEX)
    string(REGEX MATCHALL ".." HEX_CHARS "${file_content}")
    set(FORMATTED_HEX "")
    set(COUNT 0)
    foreach(char IN LISTS HEX_CHARS)
        string(APPEND FORMATTED_HEX "0x${char}, ")
        math(EXPR COUNT "${COUNT} + 1")
        if(COUNT EQUAL 16)
            string(APPEND FORMATTED_HEX "`n")
            set(COUNT 0)
        endif()
    endforeach()
    file(APPEND "${OUT_FILE}" "static const unsigned char ${var_name}[] = {`n${FORMATTED_HEX}0x00`n};`n`n")
endfunction()

embed_file("${SRC_DIR}/djot.lua" "src_djot_lua")
embed_file("${SRC_DIR}/djot/ast.lua" "src_djot_ast_lua")
embed_file("${SRC_DIR}/djot/attributes.lua" "src_djot_attributes_lua")
embed_file("${SRC_DIR}/djot/block.lua" "src_djot_block_lua")
embed_file("${SRC_DIR}/djot/filter.lua" "src_djot_filter_lua")
embed_file("${SRC_DIR}/djot/html.lua" "src_djot_html_lua")
embed_file("${SRC_DIR}/djot/inline.lua" "src_djot_inline_lua")
embed_file("${SRC_DIR}/djot/json.lua" "src_djot_json_lua")
